# Generated by Django 5.1.1 on 2025-09-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("parent", "Parent"), ("driver", "Driver")],
                default="parent",
                max_length=10,
            ),
        ),
    ]
