# Generated by Django 5.1.1 on 2025-09-21 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VanAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("van_number", models.CharField(max_length=20, unique=True)),
                ("van_model", models.CharField(blank=True, max_length=100)),
                ("capacity", models.PositiveIntegerField(default=20)),
                ("route_name", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "driver"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="van_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["van_number"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "accuracy",
                    models.FloatField(
                        blank=True, help_text="GPS accuracy in meters", null=True
                    ),
                ),
                (
                    "speed",
                    models.FloatField(blank=True, help_text="Speed in km/h", null=True),
                ),
                (
                    "heading",
                    models.FloatField(
                        blank=True, help_text="Direction in degrees", null=True
                    ),
                ),
                (
                    "altitude",
                    models.FloatField(
                        blank=True, help_text="Altitude in meters", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this is the current location"
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "driver"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["driver", "-timestamp"],
                        name="locations_l_driver__8b64b9_idx",
                    ),
                    models.Index(
                        fields=["is_active", "driver"],
                        name="locations_l_is_acti_6bc9c4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChildVanAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("child_name", models.CharField(max_length=100)),
                ("child_grade", models.CharField(blank=True, max_length=20)),
                ("school_name", models.CharField(blank=True, max_length=200)),
                ("admission_number", models.CharField(blank=True, max_length=50)),
                ("pickup_time", models.TimeField(blank=True, null=True)),
                ("dropoff_time", models.TimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "parent"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "van_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_assignments",
                        to="locations.vanassignment",
                    ),
                ),
            ],
            options={
                "ordering": ["child_name"],
                "unique_together": {("parent", "child_name")},
            },
        ),
    ]
